FROM python:3.12-slim

WORKDIR /app
RUN pip install --no-cache-dir --upgrade pip
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/

CMD ["gunicorn", "myhub.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
