-- Fantasy Football 2026 Pre-Season Player Seed
-- 300 players ranked by projected PPR fantasy value
-- Note: Team assignments reflect knowledge through mid-2025.
-- Use the admin panel to update values as needed.

BEGIN;

-- Create ranking snapshot
INSERT INTO "ranking_snapshots" ("season", "week", "label", "notes")
VALUES (2026, 1, 'Pre-Season 2026', 'Top 300 players ranked for 2026 fantasy season (PPR)')
ON CONFLICT ("season", "week") DO NOTHING;

-- Insert players
INSERT INTO "players" ("name", "position", "team", "isActive") VALUES
-- Quarterbacks (30)
('Lamar Jackson', 'QB', 'BAL', true),
('Josh Allen', 'QB', 'BUF', true),
('Jalen Hurts', 'QB', 'PHI', true),
('Joe Burrow', 'QB', 'CIN', true),
('Patrick Mahomes', 'QB', 'KC', true),
('CJ Stroud', 'QB', 'HOU', true),
('Jordan Love', 'QB', 'GB', true),
('Anthony Richardson', 'QB', 'IND', true),
('Caleb Williams', 'QB', 'CHI', true),
('Drake Maye', 'QB', 'NE', true),
('Dak Prescott', 'QB', 'DAL', true),
('Brock Purdy', 'QB', 'SF', true),
('Sam Darnold', 'QB', 'MIN', true),
('Kirk Cousins', 'QB', 'ATL', true),
('Tua Tagovailoa', 'QB', 'MIA', true),
('Baker Mayfield', 'QB', 'TB', true),
('Trevor Lawrence', 'QB', 'JAX', true),
('Kyler Murray', 'QB', 'ARI', true),
('Matthew Stafford', 'QB', 'LAR', true),
('Justin Fields', 'QB', 'PIT', true),
('Geno Smith', 'QB', 'SEA', true),
('Bryce Young', 'QB', 'CAR', true),
('Will Levis', 'QB', 'TEN', true),
('Derek Carr', 'QB', 'NO', true),
('Bo Nix', 'QB', 'DEN', true),
('Russell Wilson', 'QB', 'PIT', true),
('Deshaun Watson', 'QB', 'CLE', true),
('Mac Jones', 'QB', 'JAX', true),
('Aidan O''Connell', 'QB', 'LV', true),
('Kenny Pickett', 'QB', 'CLE', true),
-- Running Backs (80)
('Christian McCaffrey', 'RB', 'SF', true),
('Breece Hall', 'RB', 'NYJ', true),
('Bijan Robinson', 'RB', 'ATL', true),
('Jahmyr Gibbs', 'RB', 'DET', true),
('De''Von Achane', 'RB', 'MIA', true),
('Saquon Barkley', 'RB', 'PHI', true),
('Jonathan Taylor', 'RB', 'IND', true),
('Josh Jacobs', 'RB', 'GB', true),
('Kenneth Walker III', 'RB', 'SEA', true),
('Kyren Williams', 'RB', 'LAR', true),
('Derrick Henry', 'RB', 'BAL', true),
('James Cook', 'RB', 'BUF', true),
('Isiah Pacheco', 'RB', 'KC', true),
('David Montgomery', 'RB', 'DET', true),
('Travis Etienne Jr.', 'RB', 'JAX', true),
('Rachaad White', 'RB', 'TB', true),
('Joe Mixon', 'RB', 'HOU', true),
('Brian Robinson Jr.', 'RB', 'WAS', true),
('Najee Harris', 'RB', 'PIT', true),
('Tony Pollard', 'RB', 'TEN', true),
('Aaron Jones', 'RB', 'MIN', true),
('Alvin Kamara', 'RB', 'NO', true),
('Rhamondre Stevenson', 'RB', 'NE', true),
('Jerome Ford', 'RB', 'CLE', true),
('Zamir White', 'RB', 'LV', true),
('Tank Bigsby', 'RB', 'JAX', true),
('Tyjae Spears', 'RB', 'TEN', true),
('D''Andre Swift', 'RB', 'CHI', true),
('Zach Charbonnet', 'RB', 'SEA', true),
('Chase Brown', 'RB', 'CIN', true),
('Jordan Mason', 'RB', 'SF', true),
('Devin Singletary', 'RB', 'NYG', true),
('Raheem Mostert', 'RB', 'MIA', true),
('Dameon Pierce', 'RB', 'HOU', true),
('Roschon Johnson', 'RB', 'CHI', true),
('Jaylen Warren', 'RB', 'PIT', true),
('Clyde Edwards-Helaire', 'RB', 'KC', true),
('AJ Dillon', 'RB', 'GB', true),
('Austin Ekeler', 'RB', 'WAS', true),
('Kareem Hunt', 'RB', 'KC', true),
('Jaleel McLaughlin', 'RB', 'DEN', true),
('Khalil Herbert', 'RB', 'CHI', true),
('Ezekiel Elliott', 'RB', 'DAL', true),
('Miles Sanders', 'RB', 'CAR', true),
('Craig Reynolds', 'RB', 'DET', true),
('Elijah Mitchell', 'RB', 'SF', true),
('Gus Edwards', 'RB', 'LAC', true),
('Justice Hill', 'RB', 'BAL', true),
('Ty Chandler', 'RB', 'MIN', true),
('Tyler Allgeier', 'RB', 'ATL', true),
('Cordell Patterson', 'RB', 'ATL', true),
('Sincere McCormick', 'RB', 'LV', true),
('Evan Hull', 'RB', 'IND', true),
('Keaton Mitchell', 'RB', 'BAL', true),
('Chuba Hubbard', 'RB', 'CAR', true),
('Antonio Gibson', 'RB', 'NE', true),
('Zach Moss', 'RB', 'CIN', true),
('James Conner', 'RB', 'ARI', true),
('Eric Gray', 'RB', 'NYG', true),
('Emari Demercado', 'RB', 'ARI', true),
('Alexander Mattison', 'RB', 'MIN', true),
('D''Onta Foreman', 'RB', 'CHI', true),
('Cam Akers', 'RB', 'MIN', true),
('Marlon Mack', 'RB', 'HOU', true),
('Jeff Wilson Jr.', 'RB', 'MIA', true),
('Ty Montgomery II', 'RB', 'NE', true),
('Boston Scott', 'RB', 'PHI', true),
('Samaje Perine', 'RB', 'DEN', true),
('Damien Harris', 'RB', 'BUF', true),
('Tyler Goodson', 'RB', 'CLE', true),
('Jamaal Williams', 'RB', 'NO', true),
('Patrick Taylor', 'RB', 'GB', true),
('Latavius Murray', 'RB', 'NO', true),
('Chris Rodriguez Jr.', 'RB', 'WAS', true),
('Kendre Miller', 'RB', 'NO', true),
('Kimani Vidal', 'RB', 'LAC', true),
('Myles Gaskin', 'RB', 'MIA', true),
('Deon Jackson', 'RB', 'IND', true),
-- Wide Receivers (120)
('CeeDee Lamb', 'WR', 'DAL', true),
('Ja''Marr Chase', 'WR', 'CIN', true),
('Justin Jefferson', 'WR', 'MIN', true),
('Tyreek Hill', 'WR', 'MIA', true),
('Amon-Ra St. Brown', 'WR', 'DET', true),
('A.J. Brown', 'WR', 'PHI', true),
('Puka Nacua', 'WR', 'LAR', true),
('Garrett Wilson', 'WR', 'NYJ', true),
('Drake London', 'WR', 'ATL', true),
('Tee Higgins', 'WR', 'CIN', true),
('Brandon Aiyuk', 'WR', 'SF', true),
('DJ Moore', 'WR', 'CHI', true),
('Michael Pittman Jr.', 'WR', 'IND', true),
('Marvin Harrison Jr.', 'WR', 'ARI', true),
('Chris Olave', 'WR', 'NO', true),
('DeVonta Smith', 'WR', 'PHI', true),
('Jaylen Waddle', 'WR', 'MIA', true),
('Malik Nabers', 'WR', 'NYG', true),
('Jaxon Smith-Njigba', 'WR', 'SEA', true),
('Zay Flowers', 'WR', 'BAL', true),
('DK Metcalf', 'WR', 'SEA', true),
('Terry McLaurin', 'WR', 'WAS', true),
('Jordan Addison', 'WR', 'MIN', true),
('Nico Collins', 'WR', 'HOU', true),
('Tank Dell', 'WR', 'HOU', true),
('Rashee Rice', 'WR', 'KC', true),
('Xavier Worthy', 'WR', 'KC', true),
('Brian Thomas Jr.', 'WR', 'JAX', true),
('Rome Odunze', 'WR', 'CHI', true),
('Hollywood Brown', 'WR', 'KC', true),
('Davante Adams', 'WR', 'NYJ', true),
('Calvin Ridley', 'WR', 'TEN', true),
('Stefon Diggs', 'WR', 'HOU', true),
('Cooper Kupp', 'WR', 'LAR', true),
('Mike Evans', 'WR', 'TB', true),
('Jerry Jeudy', 'WR', 'CLE', true),
('Ladd McConkey', 'WR', 'LAC', true),
('Courtland Sutton', 'WR', 'DEN', true),
('Keenan Allen', 'WR', 'CHI', true),
('Josh Downs', 'WR', 'IND', true),
('Adonai Mitchell', 'WR', 'IND', true),
('Keon Coleman', 'WR', 'BUF', true),
('Diontae Johnson', 'WR', 'CAR', true),
('Christian Watson', 'WR', 'GB', true),
('Rashid Shaheed', 'WR', 'NO', true),
('Darnell Mooney', 'WR', 'ATL', true),
('Dontayvion Wicks', 'WR', 'GB', true),
('Romeo Doubs', 'WR', 'GB', true),
('Marvin Mims Jr.', 'WR', 'DEN', true),
('Josh Palmer', 'WR', 'LAC', true),
('Quentin Johnston', 'WR', 'LAC', true),
('Tyler Boyd', 'WR', 'TEN', true),
('Adam Thielen', 'WR', 'CAR', true),
('Elijah Moore', 'WR', 'CLE', true),
('Wan''Dale Robinson', 'WR', 'NYG', true),
('Darius Slayton', 'WR', 'NYG', true),
('Gabe Davis', 'WR', 'JAX', true),
('Chris Godwin', 'WR', 'TB', true),
('Mike Williams', 'WR', 'NYJ', true),
('Khalil Shakir', 'WR', 'BUF', true),
('Rashod Bateman', 'WR', 'BAL', true),
('Jahan Dotson', 'WR', 'PHI', true),
('Alec Pierce', 'WR', 'IND', true),
('Greg Dortch', 'WR', 'ARI', true),
('Cedric Tillman', 'WR', 'CLE', true),
('Tutu Atwell', 'WR', 'LAR', true),
('Rondale Moore', 'WR', 'ARI', true),
('Michael Wilson', 'WR', 'ARI', true),
('Mecole Hardman', 'WR', 'KC', true),
('DeAndre Hopkins', 'WR', 'TEN', true),
('Kendall Hinton', 'WR', 'DEN', true),
('Allen Lazard', 'WR', 'NYJ', true),
('Brandin Cooks', 'WR', 'DAL', true),
('Ricky Pearsall', 'WR', 'SF', true),
('Charlie Jones', 'WR', 'CIN', true),
('Xavier Legette', 'WR', 'CAR', true),
('KJ Osborn', 'WR', 'NE', true),
('Odell Beckham Jr.', 'WR', 'MIA', true),
('Chase Claypool', 'WR', 'CHI', true),
('Kendrick Bourne', 'WR', 'NE', true),
('Devin Duvernay', 'WR', 'BAL', true),
('Parris Campbell', 'WR', 'NYG', true),
('Noah Brown', 'WR', 'HOU', true),
('River Cracraft', 'WR', 'SF', true),
('Justin Watson', 'WR', 'KC', true),
('Equanimeous St. Brown', 'WR', 'CHI', true),
('Sterling Shepard', 'WR', 'NYG', true),
('Kadarius Toney', 'WR', 'KC', true),
('Skyy Moore', 'WR', 'KC', true),
('Van Jefferson', 'WR', 'ATL', true),
('Isaiah McKenzie', 'WR', 'BUF', true),
('Tyler Johnson', 'WR', 'TB', true),
('Trenton Irwin', 'WR', 'CIN', true),
('Lil''Jordan Humphrey', 'WR', 'NO', true),
('Demarcus Robinson', 'WR', 'LAR', true),
('Zay Jones', 'WR', 'JAX', true),
('Robert Woods', 'WR', 'TEN', true),
('Russell Gage', 'WR', 'TB', true),
('John Metchie III', 'WR', 'HOU', true),
('Jameson Williams', 'WR', 'DET', true),
('Velus Jones Jr.', 'WR', 'CHI', true),
('Tyquan Thornton', 'WR', 'NE', true),
('Kayshon Boutte', 'WR', 'NE', true),
('Jermaine Burton', 'WR', 'CIN', true),
('Danny Gray', 'WR', 'SF', true),
('Jakobi Meyers', 'WR', 'LV', true),
('Devontez Walker', 'WR', 'BAL', true),
('Bo Melton', 'WR', 'SEA', true),
('Nelson Agholor', 'WR', 'NE', true),
('Deven Thompkins', 'WR', 'TB', true),
('Justin Shorter', 'WR', 'PIT', true),
('Luke McCaffrey', 'WR', 'WAS', true),
('Malik Washington', 'WR', 'DEN', true),
('Donovan Peoples-Jones', 'WR', 'CLE', true),
('Kalif Raymond', 'WR', 'DET', true),
('DJ Chark Jr.', 'WR', 'LAR', true),
('JuJu Smith-Schuster', 'WR', 'NE', true),
-- Tight Ends (50)
('Sam LaPorta', 'TE', 'DET', true),
('Travis Kelce', 'TE', 'KC', true),
('Mark Andrews', 'TE', 'BAL', true),
('Trey McBride', 'TE', 'ARI', true),
('George Kittle', 'TE', 'SF', true),
('Dallas Goedert', 'TE', 'PHI', true),
('T.J. Hockenson', 'TE', 'MIN', true),
('Kyle Pitts', 'TE', 'ATL', true),
('Evan Engram', 'TE', 'JAX', true),
('David Njoku', 'TE', 'CLE', true),
('Pat Freiermuth', 'TE', 'PIT', true),
('Jake Ferguson', 'TE', 'DAL', true),
('Isaiah Likely', 'TE', 'BAL', true),
('Tucker Kraft', 'TE', 'GB', true),
('Luke Musgrave', 'TE', 'GB', true),
('Cole Kmet', 'TE', 'CHI', true),
('Dalton Kincaid', 'TE', 'BUF', true),
('Chigoziem Okonkwo', 'TE', 'TEN', true),
('Tyler Higbee', 'TE', 'LAR', true),
('Juwan Johnson', 'TE', 'NO', true),
('Jonnu Smith', 'TE', 'ATL', true),
('Hunter Henry', 'TE', 'NE', true),
('Mike Gesicki', 'TE', 'NE', true),
('Daniel Bellinger', 'TE', 'NYG', true),
('Zach Ertz', 'TE', 'WAS', true),
('Dawson Knox', 'TE', 'BUF', true),
('Noah Fant', 'TE', 'SEA', true),
('Tyler Conklin', 'TE', 'NYJ', true),
('Cade Otton', 'TE', 'TB', true),
('Gerald Everett', 'TE', 'LAC', true),
('James Mitchell', 'TE', 'DET', true),
('Josh Whyle', 'TE', 'CIN', true),
('Logan Thomas', 'TE', 'WAS', true),
('Austin Hooper', 'TE', 'TEN', true),
('Durham Smythe', 'TE', 'MIA', true),
('Will Dissly', 'TE', 'LAC', true),
('Marcedes Lewis', 'TE', 'GB', true),
('Robert Tonyan', 'TE', 'CHI', true),
('Cameron Brate', 'TE', 'TB', true),
('Tommy Tremble', 'TE', 'CAR', true),
('Ben Sinnott', 'TE', 'WAS', true),
('Brock Wright', 'TE', 'DET', true),
('Kylen Granson', 'TE', 'IND', true),
('Tanner Hudson', 'TE', 'NYG', true),
('Eric Saubert', 'TE', 'DEN', true),
('Charlie Woerner', 'TE', 'SF', true),
('MyCole Pruitt', 'TE', 'ATL', true),
('Irv Smith Jr.', 'TE', 'CIN', true),
('Donald Parham Jr.', 'TE', 'LAC', true),
('Mo Alie-Cox', 'TE', 'IND', true),
-- Kickers (20)
('Justin Tucker', 'K', 'BAL', true),
('Brandon Aubrey', 'K', 'DAL', true),
('Evan McPherson', 'K', 'CIN', true),
('Harrison Butker', 'K', 'KC', true),
('Tyler Bass', 'K', 'BUF', true),
('Jake Moody', 'K', 'SF', true),
('Jake Elliott', 'K', 'PHI', true),
('Cairo Santos', 'K', 'CHI', true),
('Matt Gay', 'K', 'IND', true),
('Ryan Succop', 'K', 'TB', true),
('Chris Boswell', 'K', 'PIT', true),
('Wil Lutz', 'K', 'DEN', true),
('Ka''imi Fairbairn', 'K', 'HOU', true),
('Cameron Dicker', 'K', 'LAC', true),
('Daniel Carlson', 'K', 'LV', true),
('Younghoe Koo', 'K', 'ATL', true),
('Dustin Hopkins', 'K', 'CLE', true),
('Jason Myers', 'K', 'SEA', true),
('Nick Folk', 'K', 'NE', true),
('Graham Gano', 'K', 'NYG', true)
ON CONFLICT ("name") DO NOTHING;

-- Insert player values linked to the 2026 Week 1 snapshot
INSERT INTO "player_values" ("playerId", "snapshotId", "value")
SELECT p.id, s.id, v.val
FROM (VALUES
  -- QBs
  ('Lamar Jackson', 82),
  ('Josh Allen', 80),
  ('Jalen Hurts', 78),
  ('Joe Burrow', 76),
  ('Patrick Mahomes', 75),
  ('CJ Stroud', 65),
  ('Jordan Love', 63),
  ('Anthony Richardson', 61),
  ('Caleb Williams', 60),
  ('Drake Maye', 58),
  ('Dak Prescott', 55),
  ('Brock Purdy', 53),
  ('Sam Darnold', 50),
  ('Kirk Cousins', 49),
  ('Tua Tagovailoa', 48),
  ('Baker Mayfield', 47),
  ('Trevor Lawrence', 45),
  ('Kyler Murray', 44),
  ('Matthew Stafford', 42),
  ('Justin Fields', 41),
  ('Geno Smith', 38),
  ('Bryce Young', 36),
  ('Will Levis', 35),
  ('Derek Carr', 33),
  ('Bo Nix', 45),
  ('Russell Wilson', 35),
  ('Deshaun Watson', 23),
  ('Mac Jones', 28),
  ('Aidan O''Connell', 25),
  ('Kenny Pickett', 30),
  -- RBs
  ('Christian McCaffrey', 99),
  ('Breece Hall', 89),
  ('Bijan Robinson', 87),
  ('Jahmyr Gibbs', 86),
  ('De''Von Achane', 84),
  ('Saquon Barkley', 82),
  ('Jonathan Taylor', 80),
  ('Josh Jacobs', 76),
  ('Kenneth Walker III', 74),
  ('Kyren Williams', 73),
  ('Derrick Henry', 72),
  ('James Cook', 70),
  ('Isiah Pacheco', 67),
  ('David Montgomery', 65),
  ('Travis Etienne Jr.', 63),
  ('Rachaad White', 62),
  ('Joe Mixon', 61),
  ('Brian Robinson Jr.', 58),
  ('Najee Harris', 56),
  ('Tony Pollard', 55),
  ('Aaron Jones', 54),
  ('Alvin Kamara', 52),
  ('Rhamondre Stevenson', 50),
  ('Jerome Ford', 48),
  ('Zamir White', 46),
  ('Tank Bigsby', 44),
  ('Tyjae Spears', 44),
  ('D''Andre Swift', 43),
  ('Zach Charbonnet', 43),
  ('Chase Brown', 42),
  ('Jordan Mason', 41),
  ('Devin Singletary', 38),
  ('Raheem Mostert', 36),
  ('Dameon Pierce', 35),
  ('Roschon Johnson', 34),
  ('Jaylen Warren', 34),
  ('Clyde Edwards-Helaire', 33),
  ('AJ Dillon', 32),
  ('Austin Ekeler', 32),
  ('Kareem Hunt', 31),
  ('Jaleel McLaughlin', 30),
  ('Khalil Herbert', 30),
  ('Ezekiel Elliott', 29),
  ('Miles Sanders', 28),
  ('Craig Reynolds', 25),
  ('Elijah Mitchell', 25),
  ('Gus Edwards', 25),
  ('Justice Hill', 24),
  ('Ty Chandler', 23),
  ('Tyler Allgeier', 23),
  ('Cordell Patterson', 22),
  ('Sincere McCormick', 22),
  ('Evan Hull', 21),
  ('Keaton Mitchell', 21),
  ('Chuba Hubbard', 21),
  ('Antonio Gibson', 21),
  ('Zach Moss', 20),
  ('James Conner', 20),
  ('Eric Gray', 18),
  ('Emari Demercado', 18),
  ('Alexander Mattison', 18),
  ('D''Onta Foreman', 17),
  ('Cam Akers', 17),
  ('Marlon Mack', 16),
  ('Jeff Wilson Jr.', 16),
  ('Ty Montgomery II', 15),
  ('Boston Scott', 15),
  ('Samaje Perine', 15),
  ('Damien Harris', 15),
  ('Tyler Goodson', 13),
  ('Jamaal Williams', 13),
  ('Patrick Taylor', 13),
  ('Latavius Murray', 12),
  ('Chris Rodriguez Jr.', 22),
  ('Kendre Miller', 20),
  ('Kimani Vidal', 18),
  ('Myles Gaskin', 12),
  ('Deon Jackson', 11),
  -- WRs
  ('CeeDee Lamb', 97),
  ('Ja''Marr Chase', 95),
  ('Justin Jefferson', 94),
  ('Tyreek Hill', 90),
  ('Amon-Ra St. Brown', 88),
  ('A.J. Brown', 85),
  ('Puka Nacua', 83),
  ('Garrett Wilson', 81),
  ('Drake London', 79),
  ('Tee Higgins', 78),
  ('Brandon Aiyuk', 76),
  ('DJ Moore', 74),
  ('Michael Pittman Jr.', 72),
  ('Marvin Harrison Jr.', 71),
  ('Chris Olave', 68),
  ('DeVonta Smith', 67),
  ('Jaylen Waddle', 66),
  ('Malik Nabers', 65),
  ('Jaxon Smith-Njigba', 64),
  ('Zay Flowers', 63),
  ('DK Metcalf', 61),
  ('Terry McLaurin', 60),
  ('Jordan Addison', 58),
  ('Nico Collins', 57),
  ('Tank Dell', 56),
  ('Rashee Rice', 55),
  ('Xavier Worthy', 54),
  ('Brian Thomas Jr.', 53),
  ('Rome Odunze', 51),
  ('Hollywood Brown', 50),
  ('Davante Adams', 48),
  ('Calvin Ridley', 47),
  ('Stefon Diggs', 46),
  ('Cooper Kupp', 45),
  ('Mike Evans', 44),
  ('Jerry Jeudy', 43),
  ('Ladd McConkey', 52),
  ('Courtland Sutton', 43),
  ('Keenan Allen', 42),
  ('Josh Downs', 42),
  ('Adonai Mitchell', 41),
  ('Keon Coleman', 41),
  ('Diontae Johnson', 40),
  ('Christian Watson', 39),
  ('Rashid Shaheed', 38),
  ('Darnell Mooney', 37),
  ('Dontayvion Wicks', 36),
  ('Romeo Doubs', 36),
  ('Marvin Mims Jr.', 35),
  ('Josh Palmer', 35),
  ('Quentin Johnston', 34),
  ('Tyler Boyd', 34),
  ('Adam Thielen', 33),
  ('Elijah Moore', 32),
  ('Wan''Dale Robinson', 32),
  ('Darius Slayton', 31),
  ('Gabe Davis', 31),
  ('Chris Godwin', 40),
  ('Mike Williams', 30),
  ('Khalil Shakir', 39),
  ('Rashod Bateman', 30),
  ('Jahan Dotson', 30),
  ('Alec Pierce', 29),
  ('Greg Dortch', 28),
  ('Cedric Tillman', 28),
  ('Tutu Atwell', 27),
  ('Rondale Moore', 27),
  ('Michael Wilson', 26),
  ('Mecole Hardman', 26),
  ('DeAndre Hopkins', 38),
  ('Kendall Hinton', 25),
  ('Allen Lazard', 25),
  ('Brandin Cooks', 25),
  ('Ricky Pearsall', 30),
  ('Charlie Jones', 25),
  ('Xavier Legette', 24),
  ('KJ Osborn', 23),
  ('Odell Beckham Jr.', 22),
  ('Chase Claypool', 22),
  ('Kendrick Bourne', 22),
  ('Devin Duvernay', 21),
  ('Parris Campbell', 21),
  ('Noah Brown', 21),
  ('River Cracraft', 20),
  ('Justin Watson', 20),
  ('Equanimeous St. Brown', 20),
  ('Sterling Shepard', 19),
  ('Kadarius Toney', 19),
  ('Skyy Moore', 19),
  ('Van Jefferson', 18),
  ('Isaiah McKenzie', 18),
  ('Tyler Johnson', 18),
  ('Trenton Irwin', 17),
  ('Lil''Jordan Humphrey', 17),
  ('Demarcus Robinson', 16),
  ('Zay Jones', 16),
  ('Robert Woods', 16),
  ('Russell Gage', 15),
  ('John Metchie III', 15),
  ('Jameson Williams', 28),
  ('Velus Jones Jr.', 15),
  ('Tyquan Thornton', 15),
  ('Kayshon Boutte', 14),
  ('Jermaine Burton', 14),
  ('Danny Gray', 14),
  ('Jakobi Meyers', 28),
  ('Devontez Walker', 14),
  ('Bo Melton', 13),
  ('Nelson Agholor', 13),
  ('Deven Thompkins', 12),
  ('Justin Shorter', 12),
  ('Luke McCaffrey', 18),
  ('Malik Washington', 16),
  ('Donovan Peoples-Jones', 18),
  ('Kalif Raymond', 14),
  ('DJ Chark Jr.', 15),
  ('JuJu Smith-Schuster', 13),
  -- TEs
  ('Sam LaPorta', 77),
  ('Travis Kelce', 75),
  ('Mark Andrews', 73),
  ('Trey McBride', 70),
  ('George Kittle', 68),
  ('Dallas Goedert', 65),
  ('T.J. Hockenson', 60),
  ('Kyle Pitts', 58),
  ('Evan Engram', 55),
  ('David Njoku', 53),
  ('Pat Freiermuth', 51),
  ('Jake Ferguson', 50),
  ('Isaiah Likely', 48),
  ('Tucker Kraft', 45),
  ('Luke Musgrave', 44),
  ('Cole Kmet', 42),
  ('Dalton Kincaid', 42),
  ('Chigoziem Okonkwo', 40),
  ('Tyler Higbee', 38),
  ('Juwan Johnson', 36),
  ('Jonnu Smith', 35),
  ('Hunter Henry', 34),
  ('Mike Gesicki', 33),
  ('Daniel Bellinger', 32),
  ('Zach Ertz', 31),
  ('Dawson Knox', 30),
  ('Noah Fant', 29),
  ('Tyler Conklin', 28),
  ('Cade Otton', 27),
  ('Gerald Everett', 26),
  ('James Mitchell', 25),
  ('Josh Whyle', 24),
  ('Logan Thomas', 23),
  ('Austin Hooper', 22),
  ('Durham Smythe', 21),
  ('Will Dissly', 20),
  ('Marcedes Lewis', 18),
  ('Robert Tonyan', 17),
  ('Cameron Brate', 17),
  ('Tommy Tremble', 16),
  ('Ben Sinnott', 25),
  ('Brock Wright', 16),
  ('Kylen Granson', 15),
  ('Tanner Hudson', 15),
  ('Eric Saubert', 14),
  ('Charlie Woerner', 13),
  ('MyCole Pruitt', 13),
  ('Irv Smith Jr.', 20),
  ('Donald Parham Jr.', 15),
  ('Mo Alie-Cox', 15),
  -- Kickers
  ('Justin Tucker', 55),
  ('Brandon Aubrey', 53),
  ('Evan McPherson', 50),
  ('Harrison Butker', 48),
  ('Tyler Bass', 46),
  ('Jake Moody', 45),
  ('Jake Elliott', 44),
  ('Cairo Santos', 42),
  ('Matt Gay', 42),
  ('Ryan Succop', 40),
  ('Chris Boswell', 40),
  ('Wil Lutz', 38),
  ('Ka''imi Fairbairn', 38),
  ('Cameron Dicker', 37),
  ('Daniel Carlson', 37),
  ('Younghoe Koo', 36),
  ('Dustin Hopkins', 35),
  ('Jason Myers', 35),
  ('Nick Folk', 33),
  ('Graham Gano', 33)
) AS v(pname, val)
JOIN "players" p ON p.name = v.pname
CROSS JOIN (SELECT id FROM "ranking_snapshots" WHERE season = 2026 AND week = 1) s
ON CONFLICT ("playerId", "snapshotId") DO UPDATE SET value = EXCLUDED.value;

COMMIT;
